org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2

mod_id=happy_ghast_overhaul
mod_name=Happy Ghast Overhaul
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.apm23.happyghastoverhaul
